-- Migration: Contract Change Requests & Cost Categories
-- Generated by Antigravity for CVR Project

-- 1. Create Cost Categories
CREATE TABLE IF NOT EXISTS cost_categories (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  name text not null,
  description text,
  group_name text,
  is_active boolean default true,
  sort_order integer
);

-- Enable RLS for cost_categories
ALTER TABLE cost_categories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable read access for all users" ON cost_categories;
CREATE POLICY "Enable read access for all users" ON cost_categories FOR SELECT USING (true);
-- Also add a permissive write policy if this is for dev/migration
DROP POLICY IF EXISTS "Enable insert for all authenticated" ON cost_categories;
CREATE POLICY "Enable insert for all authenticated" ON cost_categories FOR INSERT WITH CHECK (auth.role() = 'authenticated');


-- 2. Update Contract Changes Table
-- The table 'contract_changes' already exists in schema.sql but we need to ensure all columns from the migration pack are present.
-- We use DO blocks to add columns safely if they don't exist.

DO $$
BEGIN
    -- Add columns if they don't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'contract_changes' AND column_name = 'title') THEN
        ALTER TABLE contract_changes ADD COLUMN title text;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'contract_changes' AND column_name = 'reason_for_change') THEN
        ALTER TABLE contract_changes ADD COLUMN reason_for_change text;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'contract_changes' AND column_name = 'customer_reference') THEN
        ALTER TABLE contract_changes ADD COLUMN customer_reference text;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'contract_changes' AND column_name = 'commercial_owner') THEN
        ALTER TABLE contract_changes ADD COLUMN commercial_owner uuid REFERENCES public.profiles(id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'contract_changes' AND column_name = 'technical_owner') THEN
        ALTER TABLE contract_changes ADD COLUMN technical_owner uuid REFERENCES public.profiles(id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'contract_changes' AND column_name = 'customer_contact') THEN
        ALTER TABLE contract_changes ADD COLUMN customer_contact text;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'contract_changes' AND column_name = 'applies_from_period') THEN
        ALTER TABLE contract_changes ADD COLUMN applies_from_period text;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'contract_changes' AND column_name = 'applies_to_period') THEN
        ALTER TABLE contract_changes ADD COLUMN applies_to_period text;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'contract_changes' AND column_name = 'is_retrospective') THEN
        ALTER TABLE contract_changes ADD COLUMN is_retrospective boolean DEFAULT false;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'contract_changes' AND column_name = 'requires_rebaseline') THEN
        ALTER TABLE contract_changes ADD COLUMN requires_rebaseline boolean DEFAULT false;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'contract_changes' AND column_name = 'risk_narrative') THEN
        ALTER TABLE contract_changes ADD COLUMN risk_narrative text;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'contract_changes' AND column_name = 'opportunity_narrative') THEN
        ALTER TABLE contract_changes ADD COLUMN opportunity_narrative text;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'contract_changes' AND column_name = 'commercial_approval_by') THEN
        ALTER TABLE contract_changes ADD COLUMN commercial_approval_by uuid REFERENCES public.profiles(id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'contract_changes' AND column_name = 'technical_approval_by') THEN
        ALTER TABLE contract_changes ADD COLUMN technical_approval_by uuid REFERENCES public.profiles(id);
    END IF;

     IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'contract_changes' AND column_name = 'approval_date') THEN
        ALTER TABLE contract_changes ADD COLUMN approval_date date;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'contract_changes' AND column_name = 'customer_approval_received') THEN
        ALTER TABLE contract_changes ADD COLUMN customer_approval_received boolean DEFAULT false;
    END IF;
    
    -- raised_by is usually created_by in our schema, but let's check if we need an explicit raised_by text or uuid.
    -- The migration pack used 'raised_by text'. Schema has 'created_by uuid'.
    -- We will add raised_by as text to support legacy/external names if needed, or map to created_by in logic.
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'contract_changes' AND column_name = 'raised_by') THEN
        ALTER TABLE contract_changes ADD COLUMN raised_by text; 
    END IF;

END $$;

-- Policies for contract_changes (Permissive for dev/migration "No RLS" mode)
ALTER TABLE contract_changes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable all access for all users" ON contract_changes;
CREATE POLICY "Enable all access for all users" ON contract_changes FOR ALL USING (true) WITH CHECK (true);

-- Previous restrictive policies removed/commented out for now
-- DROP POLICY IF EXISTS "Enable read access for all users" ON contract_changes;
-- DROP POLICY IF EXISTS "Enable insert for all authenticated" ON contract_changes;
-- ...


-- 3. Create Contract Change Period Costs (Renamed from contract_costs to avoid conflict)
CREATE TABLE IF NOT EXISTS contract_change_period_costs (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    contract_id uuid REFERENCES contract_changes(id) ON DELETE CASCADE,
    category_id uuid REFERENCES cost_categories(id),
    period text NOT NULL, -- YYYY-MM
    amount numeric NOT NULL,
    notes text,
    cost_type text DEFAULT 'forecast',
    created_at timestamptz DEFAULT now()
);

ALTER TABLE contract_change_period_costs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all access for all users" ON contract_change_period_costs;
CREATE POLICY "Enable all access for all users" ON contract_change_period_costs FOR ALL USING (true) WITH CHECK (true);


-- 4. Create Cost Breakdown (Line Items)
CREATE TABLE IF NOT EXISTS contract_change_cost_breakdown (
  id uuid primary key default gen_random_uuid(),
  contract_change_id uuid references contract_changes(id) ON DELETE CASCADE,
  category_id uuid references cost_categories(id),
  cost_delta numeric,
  notes text
);

ALTER TABLE contract_change_cost_breakdown ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all access for all users" ON contract_change_cost_breakdown;
CREATE POLICY "Enable all access for all users" ON contract_change_cost_breakdown FOR ALL USING (true) WITH CHECK (true);
